jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: 11
        server-id: github
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.GITHUB_ACTOR }}
      if: github.ref == 'refs/heads/master'
      name: deploy snapshot (github packages)
      run: ./mvnw --batch-mode -Dgpg.passphrase=$GPG_PASSPHRASE -DskipTests deploy
name: Deploy Snapshot
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
